import "./globals.css";
import { Inter } from "next/font/google";

const fm = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Messenger",
  description: "Generated by Khalid Khan",
};

const theme : string = "light";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fm.className} ${
          theme === "dark" ? "dark" : "bg-[#f5f6f8]"
        }`}
      >
        {children}
      </body>
    </html>
  );
}
